### ISSUE TITLE
Website uses a lot of CPU

### ISSUE THREAD

**Issue by eivindml** [nazikus/rhythmic-grids#2]
Love this web app. Use it on a lot of projects :) 

But I have an issue with it using a lot of CPU power. I have a new MacBook Pro with 16GB RAM etc, so shouldn't be a problem, but the fans starts to spin and my computer gets slow after a couple of minutes on the website. I feel like it's the animating lines in the hero section which causes this.

Any idea?

**Comment by nazikus** [comment]
Hey there. Yes, indeed it`s this interactive animation consumes too much CPU. We were aware of it, but didn't realize it was so bad for other users. Thanks for pointing it out.
I have removed it for now, will replace with something less intensive later. Don't forget to force refresh (cmd+F5) the page in your browser in order to ignore cached content.

Glad to hear our app comes in handy for you! Btw, how did you find this page? We haven't really promoted it yet, just wondering what were you looking for to find it? :) thanks

**Comment by eivindml** [comment]
Awesome. 😃  Thanks for quick response. 

How did I find it? Hmm. Not sure, but I remember somehow finding the Medium article, and then the link to the website. I guess I was googling something about design grids! 👍
